### PR TITLE
Italian translation for the http-api-design

### PR DESCRIPTION
**Pull request by diegomariani**
If you will appreciate a new translation, here it's an italian translation for the HTTP API design

### CODE REVIEW

**Comment by geemus** [comment]
Awesome. Could you actually just put these files inside an `it` directory as described here: https://help.gitbook.com/format/languages.html? Then I can move the existing stuff to `en` and add the `LANGS.md` file so that they can live side by side. Thanks!

**Comment by diegomariani** [comment]
Sure ! Thanks for the link, I will fix that!

**Comment by geemus** [comment]
Great. I think I made the changes to the English to have it setup properly, so hopefully it will be all ready for you to add your version as well. Thanks!

**Comment by diegomariani** [comment]
Hi @geemus I fixed the structure as you said. I hope that's good. :))

**Comment by geemus** [comment]
Hey, sorry I lost track of this. It looks like your branch removes a lot of the English, instead of just adding the italian alongside (and unfortunately wouldn't be a clean merge). Could you tweak it so that both languages will be there? Thanks!

**Pull request closed without merging**
