### PR TITLE
POST should not always return 201

### PR DESCRIPTION
**Pull request by joe-mojo**
POST should not always return 201. Moreover, in this case it should return a Location header. See http://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html#sec9.5.
PUT and POST should return this header upon resource creation

### CODE REVIEW

**Comment by geemus** [comment]
@joe-mojo Totally dropped the ball on this. Could you rebase? (I think it would mostly be moving it to the new file structure and whatnot). I think I might end up tweaking the wording a bit after-the-fact, but I think overall this makes good points and would be good to add (and would like you to still have credit).

**Comment by joe-mojo** [comment]
Too much file moved for rebasing. But I'll make a new PR.

**Comment by geemus** [comment]
@joe-mojo sorry about that. Thanks!

**Comment by joe-mojo** [comment]
done, see PR #90

**Comment by geemus** [comment]
Great, thanks!

**Pull request closed without merging**
