### PR TITLE
Add navigation links among EN pages

### PR DESCRIPTION
**Pull request by felipecao**
I've added navigation links among English version of the guide, as to provide a more fluid reading experience.

### CODE REVIEW

**Comment by brandur** [comment]
This seems like a boon to readability, but also seems like a significant impact to the project's maintainability (in that a lot of manual linking and unlinking is required when adding, removing, or re-arranging topics). I also don't think that the pages should have been broken down so far in the first place though, so that might be part of a larger conversation.

**Comment by felipecao** [comment]
@brandur I thought the same about maintainability, but I was unsure about how likely the guide was to change. Since this project is based on what seems to be a quite stable artifact (Heroku's guide), I assumed this guide there wouldn't be too many changes over time, but you're right, it might be part of a larger conversation, I clearly lack a lot of context here 😄

**Comment by geemus** [comment]
Thanks for undertaking this, definitely can see how this would be helpful.

Hmm. I guess it depends how one interacts with it. I ended up breaking it down like this because it makes for nicer navigation in the gitbook context (https://www.gitbook.com/read/book/geemus/http-api-design), in particular I thought it lent to the TOC providing a nice, clear overview. Maybe we are not linking to that clearly/prominently enough (or maybe people just prefer not to use that format). I could certainly see collapsing it back down into fewer distinct sections, maybe just 4 sections for the bigger header areas. Perhaps I should undertake that first, and then we could still have the links, but they would be less onerous to maintain. Thoughts?

As for the broader question of change, I think/hope it will continue to evolve, but probably not particularly quickly. We have continued to refine our approach to things as we add new APIs and plan for the future, and the guide hasn't kept up as well as I might like so far (but I intend to catch it up as I am able).

**Comment by felipecao** [comment]
Thanks for the feedback, guys! Reading it via gitbook is definitely a better option than moving forward with this PR, makes much more sense :) if I may, in order to drive more people into the gitbook format, I'd suggest pointing the "Summary" link on the root `README.md` file to https://geemus.gitbooks.io/http-api-design/content/, instead of a file from within the codebase, I think this would address the "linking to that clearly/prominently enough" issue. 

Best regards!

**Comment by geemus** [comment]
I've added a more prominent link here: https://github.com/interagent/http-api-design/commit/80e94c1343da8a6eae982fe239d463d1f6fd6a50

Thanks for the feedback and PR, even if it didn't land. I certainly welcome any additional feedback. I also wonder if there is a good way to split the difference (and have better raw experience while maintaining githbook experience). I certainly welcome feedback there as well.

**Pull request closed without merging**
